services:
  catalog:
    build:
      context: .
    hostname: catalog
    depends_on:
      catalog-db:
        condition: service_healthy
    restart: always
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    environment:
      - GIN_MODE=release

      # Correct variables expected by the app
      - RETAIL_CATALOG_DB_HOST=catalog-db
      - RETAIL_CATALOG_DB_PORT=3306
      - RETAIL_CATALOG_DB_USER=catalog_user
      - RETAIL_CATALOG_DB_PASSWORD=qwerty
      - RETAIL_CATALOG_DB_NAME=catalogdb

    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  catalog-db:
    image: mariadb:10.9
    hostname: catalog-db
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty
      - MYSQL_DATABASE=catalogdb
      - MYSQL_USER=catalog_user
      - MYSQL_PASSWORD=qwerty
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "catalog_user",
          "-pqwerty"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
