apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      serviceAccountName: dynamo-sa
      containers:
        - name: cart
          image: public.ecr.aws/u2p7p1b2/e-commerce:cart
          env:
            - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: SERVER_TOMCAT_ACCESSLOG_ENABLED
            - name: RETAIL_CART_PERSISTENCE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: RETAIL_CART_PERSISTENCE_PROVIDER
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: AWS_REGION
            - name: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: cart-config
                  key: RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
