apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: e-commerce
data:
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: "redis"
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: "redis://master.e-commerce-elasticache.zok58k.use1.cache.amazonaws.com:6379"
