apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: e-commerce
data:
  GIN_MODE: "release"
  RETAIL_CATALOG_DB_HOST: "e-commerce.ca9cseaugq3y.us-east-1.rds.amazonaws.com"  # replace
  RETAIL_CATALOG_DB_PORT: "3306"
  RETAIL_CATALOG_DB_NAME: "catalogdb"
  RETAIL_CATALOG_DB_USER: "admin"
  RETAIL_CATALOG_DB_PASSWORD: "Qwerty1435421d3"
