apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  GIN_MODE: "release"
  RETAIL_CATALOG_DB_HOST: "<your-rds-endpoint.amazonaws.com>"  # replace
  RETAIL_CATALOG_DB_PORT: "3306"
  RETAIL_CATALOG_DB_NAME: "catalogdb"
