apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: e-commerce
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: "postgres"
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "database-1.ca9cseaugq3y.us-east-1.rds.amazonaws.com:5432" # replace with your RDS endpoint
  RETAIL_ORDERS_MESSAGING_PROVIDER: "rabbitmq"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "rabbitmq:5672"
