apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: "postgres"
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "orders-db.xxxxxx.us-east-1.rds.amazonaws.com:5432"
  RETAIL_ORDERS_MESSAGING_PROVIDER: "rabbitmq"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "rabbitmq:5672"
