apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: public.ecr.aws/u2p7p1b2/e-commerce:order   # replace with your ECR image
          ports:
            - containerPort: 8080
          env:
            - name: RETAIL_ORDERS_PERSISTENCE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_PERSISTENCE_PROVIDER

            - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_PERSISTENCE_ENDPOINT

            - name: RETAIL_ORDERS_PERSISTENCE_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-name
            - name: RETAIL_ORDERS_PERSISTENCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-user
            - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-password

            - name: RETAIL_ORDERS_MESSAGING_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_MESSAGING_PROVIDER

            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES

            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: rabbitmq-user
            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: rabbitmq-password
          
          # Optional: readiness & liveness probes for production
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
