apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: <your ECR image>    # replace with actual image
          ports:
            - containerPort: 8080
          env:
            - name: RETAIL_ORDERS_PERSISTENCE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_PERSISTENCE_PROVIDER

            - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_PERSISTENCE_ENDPOINT

            - name: RETAIL_ORDERS_PERSISTENCE_NAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-name
            - name: RETAIL_ORDERS_PERSISTENCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-user
            - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: db-password

            - name: RETAIL_ORDERS_MESSAGING_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_MESSAGING_PROVIDER

            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: orders-config
                  key: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES

            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: rabbitmq-user
            - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-secret
                  key: rabbitmq-password
